---
- name: Setup Environment
  hosts: all
  become: true
  roles:
    - kubernetes

- name: Run Experiment
  hosts: all
  vars_files:
    - variables.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
    - name: Include role - benchmarks
      ansible.builtin.include_role:
        name: benchmarks
      loop: "{{ deployments.replicas }}"
      loop_control:
        loop_var: replicas
