---
- name: Setup Environment
  hosts: setup
  become: true
  roles:
    - kubernetes

- name: Run Benchmarks
  hosts: benchmarks
  vars_files: variables.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - benchmarks
