---
- name: Fetch Docker install script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /var/tmp/docker-install.sh
    mode: "0755"

- name: Install Docker
  ansible.builtin.command:
    cmd: /var/tmp/docker-install.sh
    creates: /usr/bin/docker

- name: Fetch K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /var/tmp/k3s-install.sh
    mode: "0755"

- name: Install K3s
  ansible.builtin.command:
    cmd: /var/tmp/k3s-install.sh --disable servicelb,traefik,local-storage,metrics-server
    creates: /usr/local/bin/k3s

- name: Install Helm
  community.general.snap:
    classic: true
    name: helm

- name: Install helm-diff plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff

- name: Install Python
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3
      - python3-pip

- name: Install kubernetes module
  ansible.builtin.pip:
    name: kubernetes
