---
- name: Delete previous namespaces
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: absent
    wait: true
  loop: "{{ deployments.roles }}"

- name: Include tasks - benchmark
  vars:
    role: "{{ item.1 }}"
    replicas: "{{ item.0 }}"
  ansible.builtin.include_tasks:
    file: benchmark.yaml
  with_community.general.cartesian:
    - "{{ deployments.replicas }}"
    - "{{ deployments.roles }}"
